# Generated by Django 2.2.7 on 2019-11-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='A', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Timestart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('15', '15'), ('30', '30'), ('45', '45'), ('60', '60'), ('75', '75'), ('90', '90'), ('105', '105'), ('120', '120'), ('135', '135'), ('150', '150'), ('165', '165')], default='30', max_length=5)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='customers.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='products.Product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservations.Table')),
                ('timestart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservations.Timestart')),
            ],
        ),
        migrations.CreateModel(
            name='Avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('date', models.DateField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail', to='reservations.Reservation')),
            ],
        ),
    ]
