# Generated by Django 2.2.7 on 2019-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avail',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
